# project1-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project1-deploy
  labels:
    app: project1-deploy
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: project1-app
    spec:
      containers:
      - name: project1-container
        image: vasanthdocuser/finance-build:6
        ports:
        - containerPort: 80
  selector:
    matchLabels:
      app: project1-app
---
# nodeport-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: project1-np-service
  labels:
    app: project1-app-sr	
spec:
  selector:
    app: project1-app

  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
